<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MT4ServerApi">
      <HintPath>MT4ServerApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
