//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTradeEA2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EAForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EAForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTradeEA2.EAForm", typeof(EAForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=375,Y=16}.
        /// </summary>
        public static System.Drawing.Point bgw_loadChartData_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bgw_loadChartData.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=907,Y=16}.
        /// </summary>
        public static System.Drawing.Point bgwBroberQuote_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bgwBroberQuote.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=922,Y=48}.
        /// </summary>
        public static System.Drawing.Point bgwMarketQuote_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bgwMarketQuote.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1061,Y=16}.
        /// </summary>
        public static System.Drawing.Point timer_AccountPosionRefresh_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_AccountPosionRefresh.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1282,Y=16}.
        /// </summary>
        public static System.Drawing.Point timer_chartDataLoad_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_chartDataLoad.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=177,Y=16}.
        /// </summary>
        public static System.Drawing.Point timer_dsRunningProcessing_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_dsRunningProcessing.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=543,Y=16}.
        /// </summary>
        public static System.Drawing.Point timer_eAExecute_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_eAExecute.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=692,Y=16}.
        /// </summary>
        public static System.Drawing.Point timer_eaRunningProcessing_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_eaRunningProcessing.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=45}.
        /// </summary>
        public static System.Drawing.Point timer_heartBeat_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_heartBeat.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=757,Y=45}.
        /// </summary>
        public static System.Drawing.Point timer_ParaEAExcute_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer_ParaEAExcute.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=326,Y=45}.
        /// </summary>
        public static System.Drawing.Point timerCheckPlatformConnectStatus_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerCheckPlatformConnectStatus.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=566,Y=43}.
        /// </summary>
        public static System.Drawing.Point timerGenereateTestData_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timerGenereateTestData.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
