<?xml version="1.0"?>
<ChartTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Settings>
    <BackColor>
      <A>255</A>
      <R>17</R>
      <G>17</G>
      <B>17</B>
      <ScA>1</ScA>
      <ScR>0.005605392</ScR>
      <ScG>0.005605392</ScG>
      <ScB>0.005605392</ScB>
    </BackColor>
    <ForeColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>0</ScB>
    </ForeColor>
    <GridColor>
      <A>255</A>
      <R>89</R>
      <G>89</G>
      <B>89</B>
      <ScA>1</ScA>
      <ScR>0.09989873</ScR>
      <ScG>0.09989873</ScG>
      <ScB>0.09989873</ScB>
    </GridColor>
    <CrossHairsColor>
      <A>255</A>
      <R>255</R>
      <G>165</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0.376262158</ScG>
      <ScB>0</ScB>
    </CrossHairsColor>
    <DisclaimerColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>255</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>1</ScB>
    </DisclaimerColor>
    <ScrollerBackgroundColor>
      <A>255</A>
      <R>144</R>
      <G>144</G>
      <B>144</B>
      <ScA>1</ScA>
      <ScR>0.2788943</ScR>
      <ScG>0.2788943</ScG>
      <ScB>0.2788943</ScB>
    </ScrollerBackgroundColor>
    <TrendStrokeColor>
      <A>255</A>
      <R>51</R>
      <G>51</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0.0331047662</ScR>
      <ScG>0.0331047662</ScG>
      <ScB>0.0331047662</ScB>
    </TrendStrokeColor>
    <TrendBackgroundColor>
      <A>255</A>
      <R>83</R>
      <G>83</G>
      <B>83</B>
      <ScA>1</ScA>
      <ScR>0.0865004659</ScR>
      <ScG>0.0865004659</ScG>
      <ScB>0.0865004659</ScB>
    </TrendBackgroundColor>
    <BarUpColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BarUpColor>
    <BarDownColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BarDownColor>
    <BullColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BullColor>
    <BearColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BearColor>
    <LineColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </LineColor>
    <AskColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </AskColor>
    <PriceStyle>
      <Style>Candle</Style>
      <StyleName>Candle</StyleName>
      <Parameter1 xsi:nil="true" />
      <Parameter2 xsi:nil="true" />
    </PriceStyle>
  </Settings>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>f40b0ba1-eb19-418b-bb2c-95731408ec2f</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(5)</Name>
      <DisplayName>SMA(5)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>160</G>
          <B>122</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.351532638</ScG>
          <ScB>0.194617838</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(5)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>5</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>8f517090-a89d-4f1c-a475-fad3d666ad6c</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(50)</Name>
      <DisplayName>SMA(50)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>138</R>
          <G>43</G>
          <B>226</B>
          <ScA>1</ScA>
          <ScR>0.254152119</ScR>
          <ScG>0.024157634</ScG>
          <ScB>0.7605245</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(50)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>50</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>15cedfc4-a662-4681-997b-a9059d3e6aa0</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(10)</Name>
      <DisplayName>SMA(10)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>30</R>
          <G>144</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>0.0129830325</ScR>
          <ScG>0.2788943</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(10)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>10</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="MACD">
    <DisplayName>MACD</DisplayName>
    <ID>49c25169-6079-411c-b0b4-ac21075aff64</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>MACD(12,26,9)</Name>
      <DisplayName>MACD(12,26,9)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>69</G>
          <B>0</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.0595112443</ScG>
          <ScB>0</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>2</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <CopySeries>
      <Name>Signal</Name>
      <DisplayName>Signal</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>0</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>MACD(12,26,9)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>1</ChartPanel>
    <IsOverlay>false</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <SlowPeriod>26</SlowPeriod>
    <SignalPeriod>9</SignalPeriod>
    <FastPeriod>12</FastPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>becf55a2-9e49-47b1-9703-ebbdfde9eae9</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(20)</Name>
      <DisplayName>SMA(20)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>46</R>
          <G>139</G>
          <B>87</B>
          <ScA>1</ScA>
          <ScR>0.0273208935</ScR>
          <ScG>0.258182883</ScG>
          <ScB>0.09530747</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(20)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>20</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Panels>0.775514654939415</Panels>
  <Panels>0.224485345060585</Panels>
</ChartTemplate>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     