
�<?xml version="1.0"?>
<LayoutRoot xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RootPanel Orientation="Horizontal">
    <LayoutDocumentPaneGroup Orientation="Vertical">
      <LayoutDocumentPaneGroup Orientation="Horizontal" DockHeight="1.38922465283849*">
        <LayoutDocumentPane Id="dae46d70-575f-459c-9f25-986dc504ed3d" DockWidth="0.644312423971769*">
          <LayoutDocument Title="市場報價" IsSelected="True" ContentId="c8778b3d03cd43d4a1841484c884b070" FloatingLeft="1889" FloatingTop="384" FloatingWidth="1920" FloatingHeight="503" LastActivationTimeStamp="10/02/2018 17:49:25" />
        </LayoutDocumentPane>
        <LayoutDocumentPane Id="d1fbfaa4-37f1-4a72-8dc0-6ddd9ade914c">
          <LayoutDocument Title="倫敦金 H1" IsSelected="True" ContentId="f6cb3e3849654b6b8938199ab6b422b1" FloatingLeft="20" FloatingTop="389" FloatingWidth="1920" FloatingHeight="524" LastActivationTimeStamp="10/02/2018 17:49:38" PreviousContainerId="dae46d70-575f-459c-9f25-986dc504ed3d" PreviousContainerIndex="1" />
        </LayoutDocumentPane>
      </LayoutDocumentPaneGroup>
      <LayoutDocumentPaneGroup Orientation="Horizontal" DockHeight="0.935538138995911*">
        <LayoutDocumentPane Id="e91d196a-bd3f-42ae-8d36-7cb724c54fa5" DockWidth="1.31666719203297*">
          <LayoutDocument Title="開倉部位" IsSelected="True" ContentId="7debb22b4971461d942f5d53fc58ce22" FloatingLeft="1935" FloatingTop="793" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="10/02/2018 17:46:20" />
          <LayoutDocument Title="倉位總結" ContentId="600338e8d7574de8b102ce728c485d18" FloatingLeft="1833" FloatingTop="538" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:57" />
          <LayoutDocument Title="已平倉部位" ContentId="bfaa1958151349ff9970236c51dc3080" FloatingLeft="1677" FloatingTop="543" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:58" />
          <LayoutDocument Title="未完成掛單" ContentId="ebbefb5d5e884566a68f34d2912efff1" FloatingLeft="1993" FloatingTop="730" FloatingWidth="786" FloatingHeight="367" LastActivationTimeStamp="08/22/2016 17:51:58" PreviousContainerId="e91d196a-bd3f-42ae-8d36-7cb724c54fa5" PreviousContainerIndex="3" />
          <LayoutDocument Title="已執行掛單" ContentId="3fb25d5a1a65410e88d164d9cef23e0f" FloatingLeft="2038" FloatingTop="535" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:59" />
          <LayoutDocument Title="已取消掛單" ContentId="6069eb59a9fd433784f388c7f9e40ee8" FloatingLeft="2041" FloatingTop="540" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/23/2016 09:26:54" />
        </LayoutDocumentPane>
        <LayoutDocumentPane DockWidth="0.480076505446016*">
          <LayoutDocument Title="日誌" IsSelected="True" ContentId="574fd841c0974a469050f6b29388cfb4" FloatingLeft="3135" FloatingTop="792" FloatingWidth="389" FloatingHeight="344" LastActivationTimeStamp="10/02/2018 17:46:20" />
        </LayoutDocumentPane>
        <LayoutDocumentPane>
          <LayoutDocument Title="倫敦銀 H1" IsSelected="True" IsLastFocusedDocument="True" ContentId="b0b751566c764f82b52a9a746c0402cc" FloatingLeft="1107" FloatingTop="836" FloatingWidth="1163" FloatingHeight="524" LastActivationTimeStamp="10/02/2018 17:49:42" PreviousContainerId="d1fbfaa4-37f1-4a72-8dc0-6ddd9ade914c" PreviousContainerIndex="1" />
        </LayoutDocumentPane>
      </LayoutDocumentPaneGroup>
    </LayoutDocumentPaneGroup>
  </RootPanel>
  <TopSide />
  <RightSide />
  <LeftSide />
  <BottomSide />
  <FloatingWindows />
  <Hidden />
</LayoutRoot>��
 b0b751566c764f82b52a9a746c0402cc����
��<?xml version="1.0"?>
<ChartTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Settings>
    <Name>Green Up / Red Down on dark background</Name>
    <DisplayName>綠升 / 紅降 暗背景</DisplayName>
    <BackColor>
      <A>255</A>
      <R>17</R>
      <G>17</G>
      <B>17</B>
      <ScA>1</ScA>
      <ScR>0.005605392</ScR>
      <ScG>0.005605392</ScG>
      <ScB>0.005605392</ScB>
    </BackColor>
    <ForeColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>0</ScB>
    </ForeColor>
    <GridColor>
      <A>255</A>
      <R>89</R>
      <G>89</G>
      <B>89</B>
      <ScA>1</ScA>
      <ScR>0.09989873</ScR>
      <ScG>0.09989873</ScG>
      <ScB>0.09989873</ScB>
    </GridColor>
    <CrossHairsColor>
      <A>255</A>
      <R>255</R>
      <G>165</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0.376262158</ScG>
      <ScB>0</ScB>
    </CrossHairsColor>
    <DisclaimerColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>255</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>1</ScB>
    </DisclaimerColor>
    <ScrollerBackgroundColor>
      <A>255</A>
      <R>144</R>
      <G>144</G>
      <B>144</B>
      <ScA>1</ScA>
      <ScR>0.2788943</ScR>
      <ScG>0.2788943</ScG>
      <ScB>0.2788943</ScB>
    </ScrollerBackgroundColor>
    <TrendStrokeColor>
      <A>255</A>
      <R>51</R>
      <G>51</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0.0331047662</ScR>
      <ScG>0.0331047662</ScG>
      <ScB>0.0331047662</ScB>
    </TrendStrokeColor>
    <TrendBackgroundColor>
      <A>255</A>
      <R>83</R>
      <G>83</G>
      <B>83</B>
      <ScA>1</ScA>
      <ScR>0.0865004659</ScR>
      <ScG>0.0865004659</ScG>
      <ScB>0.0865004659</ScB>
    </TrendBackgroundColor>
    <BarUpColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BarUpColor>
    <BarDownColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BarDownColor>
    <BullColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BullColor>
    <BearColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BearColor>
    <LineColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </LineColor>
    <AskColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </AskColor>
    <PriceStyle>
      <Style>Candle</Style>
      <StyleName>蠟燭圖</StyleName>
      <Parameter1 xsi:nil="true" />
      <Parameter2 xsi:nil="true" />
    </PriceStyle>
  </Settings>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>f40b0ba1-eb19-418b-bb2c-95731408ec2f</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(5)</Name>
      <DisplayName>移動平均線 (SMA)(5)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>160</G>
          <B>122</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.351532638</ScG>
          <ScB>0.194617838</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(5)</ShortName>
    <IndDigits>3</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>5</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>8f517090-a89d-4f1c-a475-fad3d666ad6c</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(50)</Name>
      <DisplayName>移動平均線 (SMA)(50)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>138</R>
          <G>43</G>
          <B>226</B>
          <ScA>1</ScA>
          <ScR>0.254152119</ScR>
          <ScG>0.024157634</ScG>
          <ScB>0.7605245</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(50)</ShortName>
    <IndDigits>3</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>50</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>15cedfc4-a662-4681-997b-a9059d3e6aa0</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(10)</Name>
      <DisplayName>移動平均線 (SMA)(10)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>30</R>
          <G>144</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>0.0129830325</ScR>
          <ScG>0.2788943</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(10)</ShortName>
    <IndDigits>3</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>10</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="MACD">
    <DisplayName>移動平均匯聚背馳指標 (MACD)</DisplayName>
    <ID>49c25169-6079-411c-b0b4-ac21075aff64</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>MACD(12,26,9)</Name>
      <DisplayName>移動平均匯聚背馳指標 (MACD)(12,26,9)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>69</G>
          <B>0</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.0595112443</ScG>
          <ScB>0</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>2</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <CopySeries>
      <Name>Signal</Name>
      <DisplayName>信號(Signal)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>0</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>MACD(12,26,9)</ShortName>
    <IndDigits>3</IndDigits>
    <ChartPanel>1</ChartPanel>
    <IsOverlay>false</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <SlowPeriod>26</SlowPeriod>
    <SignalPeriod>9</SignalPeriod>
    <FastPeriod>12</FastPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>becf55a2-9e49-47b1-9703-ebbdfde9eae9</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(20)</Name>
      <DisplayName>移動平均線 (SMA)(20)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>46</R>
          <G>139</G>
          <B>87</B>
          <ScA>1</ScA>
          <ScR>0.0273208935</ScR>
          <ScG>0.258182883</ScG>
          <ScB>0.09530747</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(20)</ShortName>
    <IndDigits>3</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>20</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Panels>0.5</Panels>
  <Panels>0.5</Panels>
</ChartTemplate>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 LLSUSD< �2������6��
 f6cb3e3849654b6b8938199ab6b422b1����
��<?xml version="1.0"?>
<ChartTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Settings>
    <Name>Green Up / Red Down on dark background</Name>
    <DisplayName>綠升 / 紅降 暗背景</DisplayName>
    <BackColor>
      <A>255</A>
      <R>17</R>
      <G>17</G>
      <B>17</B>
      <ScA>1</ScA>
      <ScR>0.005605392</ScR>
      <ScG>0.005605392</ScG>
      <ScB>0.005605392</ScB>
    </BackColor>
    <ForeColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>0</ScB>
    </ForeColor>
    <GridColor>
      <A>255</A>
      <R>89</R>
      <G>89</G>
      <B>89</B>
      <ScA>1</ScA>
      <ScR>0.09989873</ScR>
      <ScG>0.09989873</ScG>
      <ScB>0.09989873</ScB>
    </GridColor>
    <CrossHairsColor>
      <A>255</A>
      <R>255</R>
      <G>165</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0.376262158</ScG>
      <ScB>0</ScB>
    </CrossHairsColor>
    <DisclaimerColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>255</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>1</ScB>
    </DisclaimerColor>
    <ScrollerBackgroundColor>
      <A>255</A>
      <R>144</R>
      <G>144</G>
      <B>144</B>
      <ScA>1</ScA>
      <ScR>0.2788943</ScR>
      <ScG>0.2788943</ScG>
      <ScB>0.2788943</ScB>
    </ScrollerBackgroundColor>
    <TrendStrokeColor>
      <A>255</A>
      <R>51</R>
      <G>51</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0.0331047662</ScR>
      <ScG>0.0331047662</ScG>
      <ScB>0.0331047662</ScB>
    </TrendStrokeColor>
    <TrendBackgroundColor>
      <A>255</A>
      <R>83</R>
      <G>83</G>
      <B>83</B>
      <ScA>1</ScA>
      <ScR>0.0865004659</ScR>
      <ScG>0.0865004659</ScG>
      <ScB>0.0865004659</ScB>
    </TrendBackgroundColor>
    <BarUpColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BarUpColor>
    <BarDownColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BarDownColor>
    <BullColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BullColor>
    <BearColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BearColor>
    <LineColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </LineColor>
    <AskColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </AskColor>
    <PriceStyle>
      <Style>Candle</Style>
      <StyleName>蠟燭圖</StyleName>
      <Parameter1 xsi:nil="true" />
      <Parameter2 xsi:nil="true" />
    </PriceStyle>
  </Settings>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>f40b0ba1-eb19-418b-bb2c-95731408ec2f</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(5)</Name>
      <DisplayName>移動平均線 (SMA)(5)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>160</G>
          <B>122</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.351532638</ScG>
          <ScB>0.194617838</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(5)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>5</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>8f517090-a89d-4f1c-a475-fad3d666ad6c</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(50)</Name>
      <DisplayName>移動平均線 (SMA)(50)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>138</R>
          <G>43</G>
          <B>226</B>
          <ScA>1</ScA>
          <ScR>0.254152119</ScR>
          <ScG>0.024157634</ScG>
          <ScB>0.7605245</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(50)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>50</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>15cedfc4-a662-4681-997b-a9059d3e6aa0</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(10)</Name>
      <DisplayName>移動平均線 (SMA)(10)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>30</R>
          <G>144</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>0.0129830325</ScR>
          <ScG>0.2788943</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(10)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>10</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="MACD">
    <DisplayName>移動平均匯聚背馳指標 (MACD)</DisplayName>
    <ID>49c25169-6079-411c-b0b4-ac21075aff64</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>MACD(12,26,9)</Name>
      <DisplayName>移動平均匯聚背馳指標 (MACD)(12,26,9)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>69</G>
          <B>0</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.0595112443</ScG>
          <ScB>0</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>2</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <CopySeries>
      <Name>Signal</Name>
      <DisplayName>信號(Signal)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>0</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>MACD(12,26,9)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>1</ChartPanel>
    <IsOverlay>false</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <SlowPeriod>26</SlowPeriod>
    <SignalPeriod>9</SignalPeriod>
    <FastPeriod>12</FastPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>移動平均線 (SMA)</DisplayName>
    <ID>becf55a2-9e49-47b1-9703-ebbdfde9eae9</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(20)</Name>
      <DisplayName>移動平均線 (SMA)(20)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>46</R>
          <G>139</G>
          <B>87</B>
          <ScA>1</ScA>
          <ScR>0.0273208935</ScR>
          <ScG>0.258182883</ScG>
          <ScB>0.09530747</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(20)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>20</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Panels>0.5</Panels>
  <Panels>0.5</Panels>
</ChartTemplate>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 LLGUSD< �2���̮��68
 c8778b3d03cd43d4a1841484c884b070
LLGUSD
LLSUSD(
 574fd841c0974a469050f6b29388cfb4 (
 7debb22b4971461d942f5d53fc58ce22 (
 600338e8d7574de8b102ce728c485d18 (
 bfaa1958151349ff9970236c51dc3080	 (
 ebbefb5d5e884566a68f34d2912efff1 (
 3fb25d5a1a65410e88d164d9cef23e0f (
 6069eb59a9fd433784f388c7f9e40ee8 