
Å<?xml version="1.0"?>
<LayoutRoot xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RootPanel Orientation="Horizontal">
    <LayoutDocumentPaneGroup Orientation="Vertical">
      <LayoutDocumentPaneGroup Orientation="Horizontal" DockHeight="1.38922465283849*">
        <LayoutDocumentPane Id="dae46d70-575f-459c-9f25-986dc504ed3d" DockWidth="0.774371033777446*">
          <LayoutDocument Title="Market Prices" IsSelected="True" ContentId="33671e9b54614b089ef444d421901975" FloatingLeft="1889" FloatingTop="384" FloatingWidth="1920" FloatingHeight="503" LastActivationTimeStamp="09/11/2016 18:37:45" />
        </LayoutDocumentPane>
        <LayoutDocumentPane Id="697b6806-941f-41d1-9357-2e9698090fec" DockWidth="1.31853298632279*">
          <LayoutDocument Title="LLG M30" IsSelected="True" ContentId="f4aff3e4eab7458a95e909de136af7e7" FloatingLeft="2366" FloatingTop="324" FloatingWidth="1920" FloatingHeight="468" LastActivationTimeStamp="09/11/2016 18:37:45" />
        </LayoutDocumentPane>
      </LayoutDocumentPaneGroup>
      <LayoutDocumentPaneGroup Orientation="Horizontal" DockHeight="0.935538138995911*">
        <LayoutDocumentPane Id="e91d196a-bd3f-42ae-8d36-7cb724c54fa5" DockWidth="1.31666719203297*">
          <LayoutDocument Title="Open Positions" IsSelected="True" ContentId="f525337bd9c74100a787a952b88ba901" FloatingLeft="1935" FloatingTop="793" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="09/11/2016 18:37:45" />
          <LayoutDocument Title="Open Positions Summary" ContentId="b2b443cc2a924633b733a5b078290454" FloatingLeft="1833" FloatingTop="538" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:57" />
          <LayoutDocument Title="Liquidated Positions" ContentId="5e4d77e6fdf543ae86a877228e5f0e91" FloatingLeft="1677" FloatingTop="543" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:58" />
          <LayoutDocument Title="Pending Orders" ContentId="6827c29b9dbf47e4a8f56c7f585952ad" FloatingLeft="1993" FloatingTop="730" FloatingWidth="786" FloatingHeight="367" LastActivationTimeStamp="08/22/2016 17:51:58" PreviousContainerId="e91d196a-bd3f-42ae-8d36-7cb724c54fa5" PreviousContainerIndex="3" />
          <LayoutDocument Title="Executed Entry Orders" ContentId="54a7710f8c004e8c873e51d697f27234" FloatingLeft="2038" FloatingTop="535" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 17:51:59" />
          <LayoutDocument Title="Cancelled Orders" ContentId="718e54d0760d44c39e50c73d663ebdd9" FloatingLeft="2041" FloatingTop="540" FloatingWidth="786" FloatingHeight="344" LastActivationTimeStamp="08/23/2016 09:26:54" />
        </LayoutDocumentPane>
        <LayoutDocumentPane DockWidth="0.480076505446016*">
          <LayoutDocument Title="Journal" IsSelected="True" ContentId="63a7336710c14d65ba2de34a8a95585c" FloatingLeft="3135" FloatingTop="792" FloatingWidth="389" FloatingHeight="344" LastActivationTimeStamp="09/11/2016 18:37:45" />
          <LayoutDocument Title="Announcement" ContentId="13168a8b23f94ce0965db418365469eb" FloatingLeft="2572" FloatingTop="548" FloatingWidth="389" FloatingHeight="344" LastActivationTimeStamp="08/22/2016 15:48:51" />
        </LayoutDocumentPane>
        <LayoutDocumentPane DockWidth="1.20325630252101*">
          <LayoutDocument Title="LLS H1" IsSelected="True" IsLastFocusedDocument="True" ContentId="0f43af0ca4d3485aa06b70a2047aefbe" FloatingLeft="2859" FloatingTop="887" FloatingWidth="1201" FloatingHeight="577" LastActivationTimeStamp="09/11/2016 18:38:14" PreviousContainerId="697b6806-941f-41d1-9357-2e9698090fec" PreviousContainerIndex="1" />
        </LayoutDocumentPane>
      </LayoutDocumentPaneGroup>
    </LayoutDocumentPaneGroup>
  </RootPanel>
  <TopSide />
  <RightSide />
  <LeftSide />
  <BottomSide />
  <FloatingWindows />
  <Hidden />
</LayoutRoot> Ä
 0f43af0ca4d3485aa06b70a2047aefbe§ÄûÄ
ÄÄ<?xml version="1.0"?>
<ChartTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Settings>
    <BackColor>
      <A>255</A>
      <R>238</R>
      <G>238</G>
      <B>238</B>
      <ScA>1</ScA>
      <ScR>0.8549926</ScR>
      <ScG>0.8549926</ScG>
      <ScB>0.8549926</ScB>
    </BackColor>
    <ForeColor>
      <A>255</A>
      <R>33</R>
      <G>33</G>
      <B>33</B>
      <ScA>1</ScA>
      <ScR>0.0152085163</ScR>
      <ScG>0.0152085163</ScG>
      <ScB>0.0152085163</ScB>
    </ForeColor>
    <GridColor>
      <A>255</A>
      <R>89</R>
      <G>89</G>
      <B>89</B>
      <ScA>1</ScA>
      <ScR>0.09989873</ScR>
      <ScG>0.09989873</ScG>
      <ScB>0.09989873</ScB>
    </GridColor>
    <CrossHairsColor>
      <A>255</A>
      <R>255</R>
      <G>165</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0.376262158</ScG>
      <ScB>0</ScB>
    </CrossHairsColor>
    <DisclaimerColor>
      <A>255</A>
      <R>0</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </DisclaimerColor>
    <ScrollerBackgroundColor>
      <A>255</A>
      <R>204</R>
      <G>204</G>
      <B>204</B>
      <ScA>1</ScA>
      <ScR>0.603827357</ScR>
      <ScG>0.603827357</ScG>
      <ScB>0.603827357</ScB>
    </ScrollerBackgroundColor>
    <TrendStrokeColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>255</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>1</ScB>
    </TrendStrokeColor>
    <TrendBackgroundColor>
      <A>255</A>
      <R>153</R>
      <G>153</G>
      <B>153</B>
      <ScA>1</ScA>
      <ScR>0.3185468</ScR>
      <ScG>0.3185468</ScG>
      <ScB>0.3185468</ScB>
    </TrendBackgroundColor>
    <BarUpColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BarUpColor>
    <BarDownColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BarDownColor>
    <BullColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BullColor>
    <BearColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BearColor>
    <LineColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </LineColor>
    <AskColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </AskColor>
    <PriceStyle>
      <Style>Candle</Style>
      <StyleName>Candle</StyleName>
      <Parameter1 xsi:nil="true" />
      <Parameter2 xsi:nil="true" />
    </PriceStyle>
  </Settings>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>f40b0ba1-eb19-418b-bb2c-95731408ec2f</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(5)</Name>
      <DisplayName>SMA(5)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>160</G>
          <B>122</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.351532638</ScG>
          <ScB>0.194617838</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(5)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>5</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>8f517090-a89d-4f1c-a475-fad3d666ad6c</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(50)</Name>
      <DisplayName>SMA(50)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>138</R>
          <G>43</G>
          <B>226</B>
          <ScA>1</ScA>
          <ScR>0.254152119</ScR>
          <ScG>0.024157634</ScG>
          <ScB>0.7605245</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(50)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>50</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>15cedfc4-a662-4681-997b-a9059d3e6aa0</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(10)</Name>
      <DisplayName>SMA(10)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>30</R>
          <G>144</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>0.0129830325</ScR>
          <ScG>0.2788943</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(10)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>10</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="MACD">
    <DisplayName>MACD</DisplayName>
    <ID>49c25169-6079-411c-b0b4-ac21075aff64</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>MACD(12,26,9)</Name>
      <DisplayName>MACD(12,26,9)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>69</G>
          <B>0</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.0595112443</ScG>
          <ScB>0</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>2</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <CopySeries>
      <Name>Signal</Name>
      <DisplayName>Signal</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>0</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>MACD(12,26,9)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>1</ChartPanel>
    <IsOverlay>false</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <SlowPeriod>26</SlowPeriod>
    <SignalPeriod>9</SignalPeriod>
    <FastPeriod>12</FastPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>becf55a2-9e49-47b1-9703-ebbdfde9eae9</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(20)</Name>
      <DisplayName>SMA(20)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>46</R>
          <G>139</G>
          <B>87</B>
          <ScA>1</ScA>
          <ScR>0.0273208935</ScR>
          <ScG>0.258182883</ScG>
          <ScB>0.09530747</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(20)</ShortName>
    <IndDigits>2</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>20</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Panels>0.775514654939415</Panels>
  <Panels>0.224485345060585</Panels>
</ChartTemplate>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            LLSUSD< Ë2Ë‡®ßöü≠4 Ä
 f4aff3e4eab7458a95e909de136af7e7§ÄûÄ
ÄÄ<?xml version="1.0"?>
<ChartTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Settings>
    <PriceStyle>
      <Style>Candle</Style>
      <StyleName>Candle</StyleName>
      <Parameter1 xsi:nil="true" />
      <Parameter2 xsi:nil="true" />
    </PriceStyle>
    <BackColor>
      <A>255</A>
      <R>238</R>
      <G>238</G>
      <B>238</B>
      <ScA>1</ScA>
      <ScR>0.8549926</ScR>
      <ScG>0.8549926</ScG>
      <ScB>0.8549926</ScB>
    </BackColor>
    <ForeColor>
      <A>255</A>
      <R>33</R>
      <G>33</G>
      <B>33</B>
      <ScA>1</ScA>
      <ScR>0.0152085163</ScR>
      <ScG>0.0152085163</ScG>
      <ScB>0.0152085163</ScB>
    </ForeColor>
    <GridColor>
      <A>255</A>
      <R>89</R>
      <G>89</G>
      <B>89</B>
      <ScA>1</ScA>
      <ScR>0.09989873</ScR>
      <ScG>0.09989873</ScG>
      <ScB>0.09989873</ScB>
    </GridColor>
    <BarUpColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BarUpColor>
    <BarDownColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BarDownColor>
    <BullColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </BullColor>
    <BearColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </BearColor>
    <LineColor>
      <A>255</A>
      <R>255</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </LineColor>
    <CrossHairsColor>
      <A>255</A>
      <R>255</R>
      <G>165</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>0.376262158</ScG>
      <ScB>0</ScB>
    </CrossHairsColor>
    <DisclaimerColor>
      <A>255</A>
      <R>0</R>
      <G>0</G>
      <B>0</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0</ScG>
      <ScB>0</ScB>
    </DisclaimerColor>
    <ScrollerBackgroundColor>
      <A>255</A>
      <R>204</R>
      <G>204</G>
      <B>204</B>
      <ScA>1</ScA>
      <ScR>0.603827357</ScR>
      <ScG>0.603827357</ScG>
      <ScB>0.603827357</ScB>
    </ScrollerBackgroundColor>
    <TrendStrokeColor>
      <A>255</A>
      <R>255</R>
      <G>255</G>
      <B>255</B>
      <ScA>1</ScA>
      <ScR>1</ScR>
      <ScG>1</ScG>
      <ScB>1</ScB>
    </TrendStrokeColor>
    <TrendBackgroundColor>
      <A>255</A>
      <R>153</R>
      <G>153</G>
      <B>153</B>
      <ScA>1</ScA>
      <ScR>0.3185468</ScR>
      <ScG>0.3185468</ScG>
      <ScB>0.3185468</ScB>
    </TrendBackgroundColor>
    <AskColor>
      <A>255</A>
      <R>0</R>
      <G>221</G>
      <B>51</B>
      <ScA>1</ScA>
      <ScR>0</ScR>
      <ScG>0.7230551</ScG>
      <ScB>0.0331047662</ScB>
    </AskColor>
  </Settings>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>f40b0ba1-eb19-418b-bb2c-95731408ec2f</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(5)</Name>
      <DisplayName>SMA(5)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>160</G>
          <B>122</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.351532638</ScG>
          <ScB>0.194617838</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(5)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>5</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>8f517090-a89d-4f1c-a475-fad3d666ad6c</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(50)</Name>
      <DisplayName>SMA(50)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>138</R>
          <G>43</G>
          <B>226</B>
          <ScA>1</ScA>
          <ScR>0.254152119</ScR>
          <ScG>0.024157634</ScG>
          <ScB>0.7605245</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(50)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>50</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>15cedfc4-a662-4681-997b-a9059d3e6aa0</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(10)</Name>
      <DisplayName>SMA(10)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>30</R>
          <G>144</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>0.0129830325</ScR>
          <ScG>0.2788943</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(10)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>10</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="MACD">
    <DisplayName>MACD</DisplayName>
    <ID>49c25169-6079-411c-b0b4-ac21075aff64</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>MACD(12,26,9)</Name>
      <DisplayName>MACD(12,26,9)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>69</G>
          <B>0</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0.0595112443</ScG>
          <ScB>0</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>2</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <CopySeries>
      <Name>Signal</Name>
      <DisplayName>Signal</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>255</R>
          <G>0</G>
          <B>255</B>
          <ScA>1</ScA>
          <ScR>1</ScR>
          <ScG>0</ScG>
          <ScB>1</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>MACD(12,26,9)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>1</ChartPanel>
    <IsOverlay>false</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <SlowPeriod>26</SlowPeriod>
    <SignalPeriod>9</SignalPeriod>
    <FastPeriod>12</FastPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Indicators xsi:type="SMA">
    <DisplayName>SMA</DisplayName>
    <ID>becf55a2-9e49-47b1-9703-ebbdfde9eae9</ID>
    <indicator_minimum xsi:nil="true" />
    <indicator_maximum xsi:nil="true" />
    <use_minimum>false</use_minimum>
    <use_maximum>false</use_maximum>
    <TimeFrame>0</TimeFrame>
    <CopySeries>
      <Name>SMA(20)</Name>
      <DisplayName>SMA(20)</DisplayName>
      <Color>
        <Color2>
          <A>255</A>
          <R>46</R>
          <G>139</G>
          <B>87</B>
          <ScA>1</ScA>
          <ScR>0.0273208935</ScR>
          <ScG>0.258182883</ScG>
          <ScB>0.09530747</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Type>0</Type>
      <Style>0</Style>
      <StartIndexDraw>0</StartIndexDraw>
      <ArrowType>81</ArrowType>
      <EmptyValue>2147483647</EmptyValue>
      <Shift>0</Shift>
    </CopySeries>
    <ShortName>SMA(20)</ShortName>
    <IndDigits>1</IndDigits>
    <ChartPanel>0</ChartPanel>
    <IsOverlay>true</IsOverlay>
    <Levels>
      <Color>
        <Color2>
          <A>255</A>
          <R>50</R>
          <G>205</G>
          <B>50</B>
          <ScA>1</ScA>
          <ScR>0.0318960324</ScR>
          <ScG>0.610495567</ScG>
          <ScB>0.0318960324</ScB>
        </Color2>
      </Color>
      <Width>1</Width>
      <Style>Solid</Style>
    </Levels>
    <IndicatorPeriod>20</IndicatorPeriod>
    <PriceType>PRICE_CLOSE</PriceType>
  </Indicators>
  <Panels>0.775514654939415</Panels>
  <Panels>0.224485345060585</Panels>
</ChartTemplate>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            LLGUSD Ë2¥ÙÑóòü≠48
 33671e9b54614b089ef444d421901975
LLGUSD
LLSUSD(
 63a7336710c14d65ba2de34a8a95585c (
 f525337bd9c74100a787a952b88ba901 (
 b2b443cc2a924633b733a5b078290454 (
 5e4d77e6fdf543ae86a877228e5f0e91	 (
 6827c29b9dbf47e4a8f56c7f585952ad (
 54a7710f8c004e8c873e51d697f27234 (
 718e54d0760d44c39e50c73d663ebdd9 (
 13168a8b23f94ce0965db418365469eb 